import db from "@/services/db";

await db.divisiPanitia.createMany({
  data: [
    { id: 1, name: "Novator (BPH)" },
    { id: 2, name: "Charta (Website)" },
    { id: 3, name: "Actus (Acara)" },
    { id: 4, name: "Scriptum (Registrasi)" },
    { id: 5, name: "Pipoca (Bazaar)" },
    { id: 6, name: "Venustus (Dekorasi)" },
    { id: 7, name: "Pictorium (Dokumentasi)" },
    { id: 8, name: "Proventus (Fresh Money)" },
    { id: 9, name: "Invictus (Keamanan dan Akomodasi)" },
    { id: 10, name: "Ligatura (Media Relation)" },
    { id: 11, name: "Mercimonia (Merchandise)" },
    { id: 12, name: "Scopus (Perlengkapan)" },
    { id: 13, name: "Epistula (Publikasi)" },
    { id: 14, name: "Aureus (Sponsorship)" },
    { id: 15, name: "Aspectus (Visual)" },
  ],
});

await db.day.createMany({
  data: [
    { id: 1, code: "D01", date: new Date("2024-04-15 10:00:00.0") },
    { id: 2, code: "D02", date: new Date("2024-04-16 10:00:00.0") },
    { id: 3, code: "D03", date: new Date("2024-04-17 10:00:00.000") },
    { id: 4, code: "D04", date: new Date("2024-04-18 10:00:00.000") },
    { id: 5, code: "D05", date: new Date("2024-04-19 10:00:00.000") },
  ],
});

await db.state.createMany({
  data: [
    {
      dayId: 1,
      name: "BEM",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "DKBM",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "HIMMA",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "HIMTARA",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "HMP",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "HIMARS",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "HMDKV",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "HMFILM",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "ACES",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "HIMFERA",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "HIMSI",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "HMIF",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "I'M KOM",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Capoeira",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Fortius",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Lions Basketball",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Lions Volleyball",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Spectre",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Lions Badminton",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Lions Futsal",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Taekwondo",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Tenis Meja",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "J-Cafe",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "KataK",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "LDNC",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "TRACCE",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Qorie",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Mufomic",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Obscura",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Ulson",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "USO",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "U-Toys",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "GDC",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Mapala",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Rencang",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Robotic",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "UESC",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "UMN Programming Club",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "UMN Festival",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Mr. & Ms. UMN",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "UMN ECO",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Starlight",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "U-Biz",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "U-store",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Rumpin",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Duta Anti Narkoba",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Kompas Corner",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "UMN Medical Center",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "UMN TV",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "UMN Radio",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Ultimagz",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "UMN Documentation",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "UMN Juice",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Skystar Venture",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Student Support / Mentoring",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Campus Visit (Marketing)",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Ikatan Bikers UMN",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Ultima Aikido",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "UMN Board Game",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Nusakara Art and Design Center",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "Popsicle UMN",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "UMN Gate",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
    {
      dayId: 1,
      name: "KSPM (Kelompok Studi Pasar Modal)",
      quota: 10,
      location: "Parkiran Gedung D",
      description: "Edit deskripsi STATE mu disini",
      logo: "-",
    },
  ],
});
